from __future__ import annotations
from typing import Any

__version__: str

def is_named_pattern(ptn: str) -> bool: ...

class _FormatPatternTrait:
    def unformat(self, s: str) -> tuple[list[str], list[Any]]: ...
    def formats(self) -> list[str]: ...
    def matches(self, s: str) -> bool: ...
    def pattern(self) -> str: ...

class FormatPattern(_FormatPatternTrait): ...

class NamedFormatPattern(_FormatPatternTrait): ...
